Fixed crash when rotating device while sort popup is open
kaczmarkiewiczp/rcloneExplorer pull request #105
Opened 2018-06-05 10:05 UTC by x0b

App crashes on rotation when sort popup is open due to being recreated without a FragmentActivity context by Android.

Fixed by re-acquiring FragmentActivity when attached without context. Also saves/restores dark theme (otherwise, Android recreates the dialog in default state). Selection state is managed by Android itself.

2018-06-06 00:31 UTC, kaczmarkiewiczp commented
I tested your solution however there are some problems with it. The dialog title, and buttons are not saved. After the device is rotated, the sort dialog does not contain any buttons. More importantly however, the listener is not saved, which means that if the sort order were to be selected, the app would crash.

I'm wondering if it wouldn't be less trouble to just dismiss the dialog on device rotation. Please let me know what you think. Thanks.

2018-06-06 11:21 UTC, x0b commented
Hmm - but wouldn't the listener just point into a dead FileExplorerFragment? A clean solution might hook into onSaveInstanceState/onDestroyViewsave and
1. Save the instance state of the Sort dialog
2. In the FileExplorerFragment, save as state that the sort dialog was open and dismiss the dialog
3. When the FileExplorerFragment is recreated check for saved state and recreate the sort dialog accordingly (or use a callback interface).

2018-06-06 12:39 UTC, x0b commented
I tried a few things, but they all evolved into an ugly mess of callbacks, casts and checks. The underlying architectural problem is the fact that the listener needs to communicate with a different fragment, while both fragments have their own life cycle. 

As a result, I switched to a very simple implementation where the FileExplorerFragment restores the listener. A cleaner architecture would probably route the calls over the host Activity.

2018-06-06 23:13 UTC, patrykcoding requested changes
I tried to figure out how to do this in a clean way, but I actually like your solution. I'll try to fix the crash in the FilePicker next. 
And the locked orientation when sharing was intentional. Initially I decide to lock the orientation as I wanted to implement other features first. I'm already handling rotation in the main file explorer, but forgot to do the same in the sharing activity. I will also have to tackle that next.

Anyways, thanks for the fix. There are some styling issues with the code, however. It's concerning the [horizontal whitespace](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace). I left inline notes. If you could fix that so that the code is consistent with the rest of the project, that would be great. Thanks.

2018-06-07 15:53 UTC, x0b commented
**Re: Code Style**
Is using the Google Java Guide a general rule? Because then contributors could just auto-format on commit.

2018-06-12 20:29 UTC, kaczmarkiewiczp commented
Sorry for the delayed response, I was away for a few days.

I linked to the Google Java Guide since it's the top result when searching for Java Style Guide. However it is common practice to have a single whitespace separating reserved words (`if` or `for`) from an open parenthesis. It's also a good idea to match the style of code so that there's no noticeable difference between different contributors, and instead the code looks as if it was written by one person.

I am not sure what you mean by "auto-format on commit" though.

2018-06-12 20:29 UTC, patrykcoding approved these changes

2018-06-12 20:31 UTC, merged

2018-06-13 19:28 UTC, x0b commented
Well, my reasoning was that _if_ the Google Java Style Guide is to be used for commits on this project that contributors like me could just use Android Studios Support for auto-formatting in that particular style.

However, if the rest of the project has its own style than obviously it is better to keep the style consistent.